import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ContactProvider } from "@/context/ContactContext";

const mont = Montserrat({
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mont.className} antialiased w-full h-full min-h-screen flex flex-col bg-gray-100`}
      >
        <ContactProvider>{children}</ContactProvider>
      </body>
    </html>
  );
}
